name: Commit New File via Node.js

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch to commit to'
        required: true
        default: 'main'  # Default to 'main' if no branch is provided

permissions:
  contents: write  # Grant write permissions to the contents of the repository
  actions: read    # Read access to Actions (for workflow usage)

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Set to the desired Node.js version

    - name: Install dependencies
      run: |
        npm install axios  # Install the necessary dependencies

    - name: Run commitFile.js script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to access the repository
        GITHUB_REPOSITORY: ${{ github.repository }}  # Get repo in 'owner/repo' format
        TARGET_BRANCH: ${{ github.event.inputs.target_branch }}  # Target branch specified by the user
      run: |
        # Run the script from the 'scripts' folder
        node scripts/commitFiles.js
